In [1]:
import pandas as pd
from decimal import Decimal, ROUND_DOWN
import math

In [2]:
source = r'‪D:\Youtube Analysis\converting_cdlc_to_numeric_values_due_to_computation_power_deficiency.csv'

In [3]:
df = pd.read_csv(source.strip("‪u202a"), encoding="latin1")

In [4]:
df.head(5)

,channel_id,channel_name,channel_category,channel_subscription_count,total_video_count,total_view,view_1,duration_1,like_1,comment_1,...,like_18,comment_18,view_19,duration_19,like_19,comment_19,view_20,duration_20,like_20,comment_20
0,1,Rebel HQ,politics,1380000,16642,1238704230,24k,15m 46s,1.8k,290,...,11k,2101,102k,8m 11s,4k,411,323k,8m 22s,10k,2826
1,2,HasanAbi,politics,1730000,2624,825231363,103k,24m 5s,5.3k,1247,...,8.7k,1536,173k,10m 26s,6.9k,706,259k,19m 8s,9.6k,907
2,3,Ben Shapiro,politics,7220000,9134,4486472051,393k,51m 56s,13k,3138,...,4.1k,1069,21k,37m 12s,911,234,73k,15m 43s,2.6k,790
3,4,The Rubin Report,politics,3050000,9059,2210892663,34k,2m 54s,2.1k,263,...,955,120,285k,6m 6s,4.1k,685,42k,3m 12s,1.8k,177
4,5,Piers Morgan Uncensored,politics,4130000,1976,1196665802,191k,45m 13s,4.4k,977,...,1.4k,425,203k,1h 30m 2s,4k,2857,82k,21m 37s,1.6k,751

In [5]:
df.shape

(146, 86)

Converting values with unit to only numeric values from view_1 to view_20

In [4]:
col_list_view_ = []
for col_view_ in df:
    col_list_view_.append(col_view_)
col_list_view_ = col_list_view_[6:]


for num_view_ in range(0, len(col_list_view_), 4):
    for data_view_ in df[col_list_view_[num_view_]]:
        edition_view_ = df[col_list_view_[num_view_]].copy()
        #print(col_list_view_[num_view_])
        for index_view_, row_view_ in edition_view_.items():
            if 'm' in row_view_:
                edition_view_.loc[index_view_] = int(float(edition_view_.loc[index_view_].split('m')[0]) * 1000000)
                
            if 'k' in row_view_:
                edition_view_.loc[index_view_] = int(float(edition_view_.loc[index_view_].split('k')[0]) * 1000)
            # if 'M' not in row_view_ and 'K' not in row_view_ and 'm' not in row_view_ and 'k' not in row_view_ :
            #     print(edition_view_.loc[index_view_], col_list_view_[num_view_])
    df[col_list_view_[num_view_]] = edition_view_

In [7]:
df.shape

(146, 86)

Converting values with unit to only numeric values from duration_1 to duration_20

In [5]:
df.at[112, 'duration_3'] = '26m 36s'
df.at[21, 'duration_17'] = '16m 29s'

In [6]:
col_list_duration_ = []
for col_duration_ in df:
    col_list_duration_.append(col_duration_)
col_list_duration_ = col_list_duration_[7:]


for num_duration_ in range(0, len(col_list_duration_), 4):
    for data_duration_ in df[col_list_duration_[num_duration_]]:
        edition_duration_ = df[col_list_duration_[num_duration_]].copy()
        #print(col_list_duration_[num_duration_])
        for index_duration_, row_duration_ in edition_duration_.items():
            if 'h' in row_duration_ and 'm' in row_duration_ and 's' in row_duration_ :
                edition_duration_.loc[index_duration_] = float( 
                                (Decimal((int(row_duration_.split(' ')[0].split('h')[0]) * 60 ) * 60 +
                                int(row_duration_.split(' ')[1].split('m')[0]) * 60 +
                                (int(row_duration_.split(' ')[2].split('s')[0]))) / 60).quantize(Decimal("0.00"), rounding=ROUND_DOWN)
                )
                # temp_time_hms = str(time_hms)
                # if '.' in temp_time_hms:
                #     if int(temp_time_hms.split('.')[1][0]) > 5:
                #         corrected_hms =temp_time_hms.split('.')[0] + '.' + str(int(str(int(temp_time_hms.split('.')[1]) / 60).split('.')[0]))
                #         edition_duration_.loc[index_duration_] = float(corrected_hms)
                # else :
                #     print('no')
                #     edition_duration_.loc[index_duration_] = time_hms


            if 'h' not in row_duration_ and 'm' in row_duration_ and 's' in row_duration_:
                edition_duration_.loc[index_duration_] = float(
                    (Decimal((int(row_duration_.split(' ')[0].split('m')[0]) * 60 +
                    int(row_duration_.split(' ')[1].split('s')[0])) / 60)).quantize(Decimal("0.00"), rounding=ROUND_DOWN)
                )
                # if '.' in str(time_ms):
                #     temp_time_ms = str(time_ms)
                #     if int(temp_time_ms.split('.')[1][0]) > 5:
                #         corrected_ms = temp_time_ms.split('.')[0] + '.' + str(int(str(int(temp_time_ms.split('.')[1]) / 60).split('.')[0]))
                #         edition_duration_.loc[index_duration_] = float(corrected_ms)
                # else :
                #     edition_duration_.loc[index_duration_] = time_ms

            
            if 'h' not in row_duration_ and 'm' not in row_duration_ and 's' in row_duration_:
                print(row_duration_)
                print(col_list_duration_[num_duration_])
                print(row_duration_.split('s'))
                edition_duration_.loc[index_duration_] = int(row_duration_.split('s')[0])
                
            if 'h' not in row_duration_ and 's' not in row_duration_ and 'm' in row_duration_ :
                edition_duration_.loc[index_duration_] = int(row_duration_.split('m')[0])

            # if 'M' not in row_view_ and 'K' not in row_view_ and 'm' not in row_view_ and 'k' not in row_view_ :
            #     print(edition_view_.loc[index_view_], col_list_view_[num_view_])
    df[col_list_duration_[num_duration_]] = edition_duration_

Converting values with unit to only numeric values from like_1 to like_20

In [7]:
df.at[101, 'like_19'] = '1.9k'
df.at[40, 'like_2'] = '387'

In [8]:
col_list_like_ = []
for col_like_ in df:
    col_list_like_.append(col_like_)
col_list_like_ = col_list_like_[8:]


for num_like_ in range(0, len(col_list_like_), 4):
    for data_like_ in df[col_list_like_[num_like_]]:
        edition_like_ = df[col_list_like_[num_like_]].copy()
        #print(col_list_duration_[num_duration_])
        for index_like_, row_like_ in edition_like_.items():
            if 'm' in row_like_ :
                edition_like_.loc[index_like_] = int(float(edition_like_.loc[index_like_].split('m')[0]) * 1000000)
            elif 'k' in row_like_:
                edition_like_.loc[index_like_] = int(float(edition_like_.loc[index_like_].split('k')[0]) * 1000)
    df[col_list_like_[num_like_]] = edition_like_

In [12]:
df.shape

(146, 86)

In [11]:
df.head(5)

,channel_id,channel_name,channel_category,channel_subscription_count,total_video_count,total_view,view_1,duration_1,like_1,comment_1,...,like_18,comment_18,view_19,duration_19,like_19,comment_19,view_20,duration_20,like_20,comment_20
0,1,Rebel HQ,politics,1380000,16642,1238704230,24000,15.76,1800,290,...,11000,2101,102000,8.18,4000,411,323000,8.36,10000,2826
1,2,HasanAbi,politics,1730000,2624,825231363,103000,24.08,5300,1247,...,8700,1536,173000,10.43,6900,706,259000,19.13,9600,907
2,3,Ben Shapiro,politics,7220000,9134,4486472051,393000,51.93,13000,3138,...,4100,1069,21000,37.2,911,234,73000,15.71,2600,790
3,4,The Rubin Report,politics,3050000,9059,2210892663,34000,2.89,2100,263,...,955,120,285000,6.09,4100,685,42000,3.2,1800,177
4,5,Piers Morgan Uncensored,politics,4130000,1976,1196665802,191000,45.21,4400,977,...,1400,425,203000,90,4000,2857,82000,21.61,1600,751

There was a value detected during the operation below that somehow was not converted to numeric value so it's done now below

In [9]:
df.at[10, 'view_12'] = 1500

Changing type to int from view_1 to view_20

In [10]:
for column_name1 in df:
    if column_name1.split('_')[0] == 'view':
        df[column_name1] = df[column_name1].astype(int)

Adding another column to the dataset.
This column is a sum of all values from view_1 to view_20

In [11]:
df['total_views_of_chosen_videos'] = 0
for column_of_views in df:
    if column_of_views.split('_')[0] == 'view':
        df['total_views_of_chosen_videos'] += df[column_of_views]

Changing type to float from duration_1 to duration_20

Another value was detected during the operation below that was not fully converted to a numeric value, now it's done by the code below.

In [12]:
df.at[91, 'duration_1'] = '73.53'

In [13]:
df.at[41, 'duration_2'] = '21.18'

In [14]:
df.at[45, 'duration_3'] = '28.25'

In [15]:
df.at[21, 'duration_5'] = '20'

In [16]:
for column_name2 in df:
    if column_name2.split('_')[0] == 'duration':
        df[column_name2] = df[column_name2].astype(float)

Adding another column to the dataset. This column is a sum of all values from duration_1 to duration_20

In [17]:
df['total_duration_of_chosen_videos_in_minute'] = 0
for column_of_duration in df:
    if column_of_duration.split('_')[0] == 'duration':
        df['total_duration_of_chosen_videos_in_minute'] += df[column_of_duration]

Changing type to int from like_1 to like_20

In [18]:
df.at[4, 'like_2'] = '8600'

In [19]:
df.at[81, 'like_2'] = '7500'

In [20]:
for column_name3 in df:
    if column_name3.split('_')[0] == 'like':
        df[column_name3] = df[column_name3].astype(int)

Adding another column to the dataset. This column is a sum of all values from like_1 to like_20

In [21]:
df['total_like_of_chosen_videos'] = 0
for column_of_like in df:
    if column_of_like.split('_')[0] == 'like':
        df['total_like_of_chosen_videos'] += df[column_of_like]

In [25]:
df

,channel_id,channel_name,channel_category,channel_subscription_count,total_video_count,total_view,view_1,duration_1,like_1,comment_1,...,duration_19,like_19,comment_19,view_20,duration_20,like_20,comment_20,total_views_of_chosen_videos,total_duration_of_chosen_videos_in_minute,total_like_of_chosen_videos
0,1,Rebel HQ,politics,1380000,16642,1238704230,24000,15.76,1800,290,...,8.18,4000,411,323000,8.36,10000,2826,1463000,206.37,68289
1,2,HasanAbi,politics,1730000,2624,825231363,103000,24.08,5300,1247,...,10.43,6900,706,259000,19.13,9600,907,5912000,496.29,204200
2,3,Ben Shapiro,politics,7220000,9134,4486472051,393000,51.93,13000,3138,...,37.20,911,234,73000,15.71,2600,790,8003000,727.55,218191
3,4,The Rubin Report,politics,3050000,9059,2210892663,34000,2.89,2100,263,...,6.09,4100,685,42000,3.20,1800,177,10266000,371.22,346955
4,5,Piers Morgan Uncensored,politics,4130000,1976,1196665802,191000,45.21,4400,977,...,90.00,4000,2857,82000,21.61,1600,751,12816000,1052.06,260232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142,HauteLeMode,fashion,983000,1187,346718304,46000,16.13,2500,140,...,34.31,19000,1803,1100000,34.21,36000,3530,3716000,429.07,142300
142,143,Loic Prigent,fashion,684000,848,138011595,135000,31.23,2500,53,...,10.65,856,43,209000,8.94,4500,94,3729000,375.75,72156
143,144,Micarah Tewers,fashion,2500000,174,387288668,606000,20.44,53000,2060,...,21.91,46000,1834,823000,17.73,54000,1749,15672000,334.61,983000
144,145,Tim Dessaint,fashion,1530000,193,142458447,95000,8.31,4500,278,...,3.79,68000,1567,433000,6.78,9100,1567,7323000,170.01,273100
145,146,Bliss Foster,fashion,385000,268,22037118,18000,28.00,1400,125,...,17.58,4100,140,74000,14.73,4600,173,3030000,1140.45,139400

Adding another column to the dataset. This column is a sum of all values from comment_1 to comment_20

In [22]:
df['total_comment_of_chosen_videos'] = 0
for column_of_comment in df:
    if column_of_comment.split('_')[0] == 'comment':
        df['total_comment_of_chosen_videos'] += df[column_of_comment]

In [397]:
df

,channel_id,channel_name,channel_category,channel_subscription_count,total_video_count,total_view,view_1,duration_1,like_1,comment_1,...,like_19,comment_19,view_20,duration_20,like_20,comment_20,total_views_of_chosen_videos,total_duration_of_chosen_videos_in_minute,total_like_of_chosen_videos,total_comment_of_chosen_videos
0,1,Rebel HQ,politics,1380000,16642,1238704230,24000,15.76,1800,290,...,4000,411,323000,8.36,10000,2826,1463000,206.37,68289,13138
1,2,HasanAbi,politics,1730000,2624,825231363,103000,24.08,5300,1247,...,6900,706,259000,19.13,9600,907,5912000,496.29,204200,54467
2,3,Ben Shapiro,politics,7220000,9134,4486472051,393000,51.93,13000,3138,...,911,234,73000,15.71,2600,790,8003000,727.55,218191,50462
3,4,The Rubin Report,politics,3050000,9059,2210892663,34000,2.89,2100,263,...,4100,685,42000,3.20,1800,177,10266000,371.22,346955,93325
4,5,Piers Morgan Uncensored,politics,4130000,1976,1196665802,191000,45.21,4400,977,...,4000,2857,82000,21.61,1600,751,12816000,1052.06,260232,143825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,142,HauteLeMode,fashion,983000,1187,346718304,46000,16.13,2500,140,...,19000,1803,1100000,34.21,36000,3530,3716000,429.07,142300,12636
142,143,Loic Prigent,fashion,684000,848,138011595,135000,31.23,2500,53,...,856,43,209000,8.94,4500,94,3729000,375.75,72156,2018
143,144,Micarah Tewers,fashion,2500000,174,387288668,606000,20.44,53000,2060,...,46000,1834,823000,17.73,54000,1749,15672000,334.61,983000,40723
144,145,Tim Dessaint,fashion,1530000,193,142458447,95000,8.31,4500,278,...,68000,1567,433000,6.78,9100,1567,7323000,170.01,273100,9208
145,146,Bliss Foster,fashion,385000,268,22037118,18000,28.00,1400,125,...,4100,140,74000,14.73,4600,173,3030000,1140.45,139400,10457

In [24]:
df['channel_category'].unique()

array(['politics', 'critical_thinking', 'science_tech', 'exercise',
       'history', 'talk', 'entertainment', 'language_', 'motivational',
       'food', 'reactional', 'travel_nature', 'asmr', 'true_crime',
       'finance', 'military', 'gaming', 'makeup', 'reality_show',
       'education', 'sports', 'fashion'], dtype=object)

In [27]:
df.to_csv('cleaning_is_done_with_you_db1.csv', index=False)